// Browser frontend: loads a ROM, runs gb-core at the Game Boy's real frame
// rate, draws to a canvas, forwards keyboard, gamepad and touch input.
//
// ./pkg is generated by scripts/build-web.(ps1|sh). It is not checked in.
import init, { Emulator } from "./pkg/gb_wasm.js";
import { KEYMAP, gamepadsMask, dpadMask, withButton, changes } from "./input.js";
import { FRAME_MS, TURBO, framesDue, nextSpeed, audioFramesDue } from "./timing.js";
import { nowSeconds, saveKey, readSave, writeSave, saveFileName } from "./saves.js";
import { AudioOut } from "./audio.js";
import { DebugPanel } from "./debugger.js";
import { MemoryView } from "./memview.js";
import { VramView } from "./vramview.js";
import { BreakpointList } from "./breakpoints.js";
import { hex } from "./format.js";
import {
  StateStore,
  SlotsPanel,
  indexedDbBackend,
  memoryBackend,
  savedAgo,
  slotForKey,
} from "./states.js";

const audio = new AudioOut();

const $ = (id) => document.getElementById(id);
const canvas = $("screen");
const ctx = canvas.getContext("2d");
const memory = new MemoryView(
  {
    section: $("mem-section"),
    view: $("mem-view"),
    addr: $("mem-addr"),
    follow: $("mem-follow"),
    prev: $("mem-prev"),
    next: $("mem-next"),
    jumps: $("mem-jumps"),
    info: $("mem-info"),
  },
  () => debug.update(emu),
);
// Kept here, not just in the emulator: Reset swaps in a new one.
const breakpoints = new BreakpointList();
const debug = new DebugPanel({
  breakpoints,
  bpAddr: $("bp-addr"),
  bpList: $("bp-list"),
  panel: $("debug-panel"),
  regs: $("regs"),
  flags: $("flags"),
  disasm: $("disasm"),
  note: $("debug-note"),
  memory,
  // Clicking a tile or map entry shows its bytes in the memory view.
  vram: new VramView(
    {
      section: $("vram-section"),
      tiles: $("vram-tiles"),
      map: $("vram-map-canvas"),
      mapChoice: $("vram-map"),
      tileBank: $("vram-bank"),
      info: $("vram-info"),
    },
    (addr) => {
      $("mem-section").open = true;
      memory.select(addr);
    },
  ),
});
// An ImageData whose pixels *are* the emulator's framebuffer in wasm memory
// (see screenImage()), so drawing a frame copies nothing on the JS side.
let screenView = null;

let emu = null;
// The loaded ROM, kept so Reset can power-cycle with it.
let rom = null;
// Where the loaded ROM's battery save lives in localStorage.
let romSaveKey = null;
// localStorage, or null where the browser refuses it (some private modes).
const storage = (() => {
  try {
    return window.localStorage;
  } catch {
    return null;
  }
})();
let rafId = 0;
let lastTime = 0;
let backlog = 0;
let framesThisSecond = 0;
let fpsTimer = 0;
let paused = false;
let speed = 1; // from the speed button: 1, 2 or 4
let turbo = false; // Space held: fast-forward at TURBO
let rewinding = false; // Backspace or the ⏪ button held: run time backwards
// Buttons held on the keyboard, and what the emulator was last told is held
// (keyboard OR gamepads OR touch), as masks indexed like gb_core::Button.
let keyMask = 0;
let sentMask = 0;
// Each finger on the on-screen controls: pointerId -> { onDpad, mask }.
const touches = new Map();

const wasm = await init(); // the wasm exports, including its memory

async function loadRom(file) {
  const bytes = new Uint8Array(await file.arrayBuffer());
  const key = await saveKey(bytes);
  persistSave(); // keep the previous game's progress before switching
  if (!boot(bytes, file.name)) {
    showStatus();
    return;
  }
  rom = bytes;
  romSaveKey = key;
  $("title").textContent = emu.title() || file.name;
  $("hint").hidden = true;
  restoreStoredSave();
  breakpoints.clear(emu); // a different game: the old addresses mean nothing
  slots.status("");
  refreshSlots();
  setPaused(false);
  showStatus();
}

/**
 * Swaps in a fresh emulator on `bytes` (a power cycle), with battery save
 * `save` plugged in first if given. If either won't load, shows why and
 * leaves the current game as it was.
 */
function boot(bytes, what, save = null) {
  let next = null;
  try {
    next = new Emulator(bytes);
    if (save) next.load_save(save, nowSeconds());
  } catch (e) {
    next?.free();
    showError(`Couldn't load ${what}: ${e.message ?? e}`);
    return false;
  }
  stop();
  emu?.free();
  emu = next;
  breakpoints.applyTo(emu);
  $("error").hidden = true;
  $("serial").textContent = "";
  emu.set_sample_rate(audio.sampleRate);
  debug.note("");
  debug.update(emu);
  sentMask = 0; // a fresh emulator has nothing held; resend what is
  syncButtons();
  return true;
}

// Reset: the DMG has no reset button, so power-cycle with the same ROM. The
// cartridge's battery keeps its save (and clock) through that.
function reset() {
  if (!rom) return;
  const save = emu?.save_data(nowSeconds()) ?? null;
  if (!boot(rom, $("title").textContent, save)) return;
  draw();
  if (!paused) start();
}

// Battery saves: stored per ROM in localStorage shortly after the game
// writes one, and whenever the page is hidden or closed.
function restoreStoredSave() {
  if (!emu.has_battery()) return setSaveStatus("");
  const stored = readSave(storage, romSaveKey);
  if (!stored) return setSaveStatus("💾 no save yet");
  try {
    emu.load_save(stored, nowSeconds());
    setSaveStatus("💾 save loaded");
  } catch (e) {
    showError(`Couldn't load the stored save: ${e.message ?? e}`);
  }
}

function persistSave() {
  if (!emu?.has_battery() || !romSaveKey) return;
  if (writeSave(storage, romSaveKey, emu.save_data(nowSeconds()))) {
    setSaveStatus(`💾 saved ${new Date().toLocaleTimeString()}`);
  } else {
    setSaveStatus("💾 this browser won't store saves: use Export .sav");
  }
}

function setSaveStatus(text) {
  $("save").textContent = text;
}

function exportSave() {
  const data = emu?.save_data(nowSeconds());
  if (!data) return;
  const url = URL.createObjectURL(new Blob([data], { type: "application/octet-stream" }));
  const link = document.createElement("a");
  link.href = url;
  link.download = saveFileName(emu.title());
  link.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

// Importing restarts the game with the imported save plugged in, like
// swapping in a cartridge that has it.
async function importSave(file) {
  if (!rom) return;
  const data = new Uint8Array(await file.arrayBuffer());
  if (!boot(rom, file.name, data)) return;
  persistSave();
  setSaveStatus(`💾 imported ${file.name}`);
  draw();
  if (!paused) start();
}

function setPaused(on) {
  paused = on;
  if (paused) stop();
  else if (emu && !rafId) start();
  if (!paused) {
    // Continuing gets past where it paused, even onto a breakpoint set there.
    emu?.resume_past_breakpoint();
    debug.note("");
  }
  showPaused();
  showStatus();
  debug.update(emu);
}

// The "Paused" cover hides the screen, so leave it off while debugging:
// stepping draws the frame as far as it has got.
function showPaused() {
  $("paused").hidden = !paused || debug.open;
}

function cycleSpeed() {
  speed = nextSpeed(speed);
  showStatus();
}

function start() {
  lastTime = performance.now();
  fpsTimer = lastTime;
  framesThisSecond = 0;
  backlog = 0;
  rafId = requestAnimationFrame(loop);
}

function stop() {
  cancelAnimationFrame(rafId);
  rafId = 0;
}

// requestAnimationFrame fires at the monitor's rate (60, 120, 144 Hz...),
// so run however many Game Boy frames are due, not one per callback.
// Fast-forward just makes more frames due; only the last one gets drawn.
// At normal speed with sound on, the audio queue sets the pace: run frames
// only when it needs topping up, so the sound card's clock drives the game
// and the sound neither crackles nor drifts. Otherwise (no sound yet, or
// fast-forward, which is muted) the wall clock does.
function loop(now) {
  if (rewinding) {
    rewindFrames(now);
    rafId = requestAnimationFrame(loop);
    return;
  }
  const audioPaced = audio.running && !turbo && speed === 1;
  let frames;
  if (audioPaced) {
    const perFrame = (audio.sampleRate * FRAME_MS) / 1000;
    frames = audioFramesDue(audio.buffered(now), audio.targetFrames, perFrame);
    backlog = 0;
  } else {
    const due = framesDue(backlog, now - lastTime, turbo ? TURBO : speed);
    backlog = due.backlog;
    frames = due.frames;
  }
  lastTime = now;
  syncButtons(); // gamepads have no events: poll them every frame
  let ran = 0;
  let hit = false; // stopped at a breakpoint
  try {
    while (ran < frames && !hit) {
      hit = emu.run_frame();
      ran++;
      const sound = emu.take_audio(); // always drain; only play it when paced
      if (audioPaced) audio.push(sound);
    }
  } catch (e) {
    stop();
    draw();
    debug.update(emu);
    showError(String(e.message ?? e));
    return;
  }
  if (ran) {
    draw();
    debug.update(emu);
  }
  collectSerial();
  countFps(now, ran);
  if (hit) {
    showBreakpointHit();
    return;
  }
  rafId = requestAnimationFrame(loop);
}

/** Pauses at a breakpoint and opens the debugger there. */
function showBreakpointHit() {
  setPaused(true);
  $("debug-panel").open = true;
  debug.note(`stopped at the breakpoint at $${hex(pcNow(), 4)}`);
  debug.update(emu);
}

function pcNow() {
  const state = emu.cpu_state();
  const pc = state.pc;
  state.free();
  return pc;
}

// Rewinding: one snapshot back per Game Boy frame due, so with snapshots
// 2 frames apart time runs backwards at double speed. Nothing runs, so
// there's no sound; the audio queue fades out, and back in afterwards.
function rewindFrames(now) {
  const due = framesDue(backlog, now - lastTime, 1);
  backlog = due.backlog;
  lastTime = now;
  let went = 0;
  while (went < due.frames && emu.rewind_step()) went++;
  if (went) {
    draw();
    debug.update(emu);
  }
  showRewind();
  countFps(now, went);
}

/** While paused, each press steps back one snapshot. */
function rewindOnce() {
  if (emu?.rewind_step()) {
    draw();
    debug.update(emu);
  }
  showRewind();
}

function setRewinding(on) {
  if (!emu || rewinding === on) return;
  rewinding = on;
  showRewind();
}

/** The ⏪ button: how much history is left, lit while rewinding. */
function showRewind() {
  const seconds = emu ? Math.floor(emu.rewind_seconds()) : 0;
  $("rewind").textContent = `⏪ ${seconds} s`;
  $("rewind").classList.toggle("fast", rewinding);
  $("rewind").setAttribute("aria-pressed", String(rewinding));
}

function draw() {
  ctx.putImageData(screenImage(), 0, 0);
}

/** The ImageData view on the framebuffer, rebuilt when it has gone stale: a
 * new emulator has its framebuffer elsewhere, and growing wasm memory
 * detaches the old ArrayBuffer (any view on it then reads as empty). */
function screenImage() {
  const ptr = emu.framebuffer_ptr();
  const data = screenView?.data;
  if (!data || data.buffer !== wasm.memory.buffer || data.byteOffset !== ptr) {
    const pixels = new Uint8ClampedArray(wasm.memory.buffer, ptr, emu.framebuffer_len());
    screenView = new ImageData(pixels, 160, 144);
  }
  return screenView;
}

function collectSerial() {
  const text = emu.take_serial();
  if (text) {
    $("serial").textContent += text;
    $("serial-panel").open = true;
  }
}

function countFps(now, ran) {
  framesThisSecond += ran;
  if (now - fpsTimer >= 1000) {
    $("fps").textContent = `${framesThisSecond} fps`;
    framesThisSecond = 0;
    fpsTimer = now;
    // Once a second, store the save if the game changed it.
    if (emu.take_save_dirty()) persistSave();
    showRewind();
  }
}

/** Updates the toolbar buttons to match the current state. */
function showStatus() {
  const loaded = Boolean(emu);
  for (const id of ["pause", "reset", "speed", "rewind", "step", "step-frame"]) {
    $(id).disabled = !loaded;
  }
  showRewind();
  const battery = Boolean(emu?.has_battery());
  for (const id of ["export-save", "import-save"]) $(id).disabled = !battery;
  $("sound").textContent = !audio.running ? "🔇 Sound off" : audio.muted ? "🔇 Muted" : "🔈 Sound";
  $("sound").setAttribute("aria-pressed", String(audio.running && !audio.muted));
  $("pause").textContent = paused ? "Resume" : "Pause";
  $("pause").setAttribute("aria-pressed", String(paused));
  const shown = turbo ? TURBO : speed;
  $("speed").textContent = `${shown}×`;
  $("speed").classList.toggle("fast", shown > 1);
  if (paused) $("fps").textContent = "paused";
}

function showError(message) {
  const el = $("error");
  el.textContent = message;
  el.hidden = false;
}

// Input
// Tells the emulator about buttons whose combined (keyboard OR gamepad) state
// changed, so letting go of a key doesn't release a button held on the pad.
function syncButtons() {
  if (!emu) return;
  let mask = keyMask | gamepadsMask(navigator.getGamepads?.());
  for (const t of touches.values()) mask |= t.mask;
  for (const [button, pressed] of changes(sentMask, mask)) {
    emu.set_button(button, pressed);
  }
  sentMask = mask;
}

/** True while typing into a text field, e.g. the debugger's address box:
 * keys then belong to the field, not the game. */
const typing = (e) => Boolean(e.target.closest?.("input, select, textarea"));

function onKey(e, pressed) {
  if (pressed && typing(e)) return;
  const button = KEYMAP[e.code];
  if (button === undefined) return;
  if (emu) e.preventDefault(); // without a game, let arrows scroll the page
  keyMask = withButton(keyMask, button, pressed);
  syncButtons();
}
addEventListener("keydown", (e) => onKey(e, true));
addEventListener("keyup", (e) => onKey(e, false));
// Switching tabs can swallow keyup events; don't leave buttons stuck down.
addEventListener("blur", () => {
  keyMask = 0;
  syncButtons();
  setTurbo(false);
  setRewinding(false);
});

// Emulator controls: P pause, R reset, F cycle speed, hold Space to fast-forward.
function setTurbo(on) {
  if (turbo === on) return;
  turbo = on;
  showStatus();
}
addEventListener("keydown", (e) => {
  if (!emu || e.ctrlKey || e.metaKey || e.altKey || typing(e)) return;
  if (e.code === "Space") {
    e.preventDefault(); // don't scroll the page
    setTurbo(true);
    return;
  }
  if (e.code === "Backspace") {
    e.preventDefault();
    if (paused) rewindOnce(); // key repeat keeps stepping back
    else setRewinding(true);
    return;
  }
  if (e.repeat) return;
  if (e.code === "KeyP") setPaused(!paused);
  else if (e.code === "KeyR") reset();
  else if (e.code === "KeyF") cycleSpeed();
  else if (e.code === "KeyM") toggleSound();
  else if (e.code === "KeyN") stepInstruction();
  else if (e.code === "KeyS") saveState(slot);
  else if (e.code === "KeyL") loadState(slot);
  else if (slotForKey(e.code)) selectSlot(slotForKey(e.code));
});
addEventListener("keyup", (e) => {
  if (e.code === "Space") setTurbo(false);
  if (e.code === "Backspace") setRewinding(false);
});
// The ⏪ button rewinds while held (mouse, pen or finger).
const rewindButton = $("rewind");
rewindButton.addEventListener("pointerdown", (e) => {
  e.preventDefault();
  try {
    rewindButton.setPointerCapture(e.pointerId);
  } catch {
    // Synthetic pointers can't be captured; pointerup still arrives.
  }
  if (paused) rewindOnce();
  else setRewinding(true);
});
for (const type of ["pointerup", "pointercancel", "lostpointercapture"]) {
  rewindButton.addEventListener(type, () => setRewinding(false));
}
rewindButton.addEventListener("contextmenu", (e) => e.preventDefault());
// Drop focus after a click: a focused button would also be "clicked" by
// Enter (Start) or Space (fast-forward) during play.
const toolbar = [
  ["pause", () => setPaused(!paused)],
  ["reset", reset],
  ["speed", cycleSpeed],
  ["export-save", exportSave],
  ["import-save", () => $("save-file").click()],
  ["sound", toggleSound],
  ["step", stepInstruction],
  ["step-frame", stepFrame],
];
for (const [id, action] of toolbar) {
  $(id).addEventListener("click", (e) => {
    action();
    e.currentTarget.blur();
  });
}
$("save-file").addEventListener("change", (e) => {
  const file = e.target.files[0];
  e.target.value = ""; // so picking the same file again still fires
  if (file) importSave(file);
});
// Store the save when the page is hidden (tab switch, phone lock) or closed.
addEventListener("visibilitychange", () => {
  if (document.visibilityState === "hidden") persistSave();
});
addEventListener("pagehide", persistSave);

// Save states: four slots per game in IndexedDB, each with a picture of
// the screen. Loading one also puts the battery save back to how it was
// then (it's part of the state); that gets stored like any other change.
const stateStore = new StateStore(indexedDbBackend());
const slots = new SlotsPanel(
  { slots: $("slots"), status: $("state-status") },
  { save: saveState, load: loadState, select: selectSlot },
);
let slot = 1; // picked with 1-4; S and L use it
stateStore.backend.ready.catch(() => {
  stateStore.backend = memoryBackend();
  slots.status("this browser won't keep save states after the page closes");
});
selectSlot(1);
refreshSlots();

function selectSlot(n) {
  slot = n;
  slots.select(n);
}

/** Redraws the slots for the game that's loaded (none: all disabled). */
async function refreshSlots() {
  const key = romSaveKey;
  let records = [];
  if (key) {
    try {
      records = await stateStore.list(key);
    } catch (e) {
      slots.status(`couldn't read save states: ${e.message ?? e}`, true);
    }
  }
  if (key === romSaveKey) slots.show(records, Boolean(emu));
}

async function saveState(n) {
  if (!emu) return;
  selectSlot(n);
  const key = romSaveKey;
  const state = emu.save_state();
  // The screen as it is now: toBlob snapshots the canvas when it's called.
  const thumb = await new Promise((resolve) => canvas.toBlob(resolve, "image/png"));
  try {
    await stateStore.save(key, n, { state, thumb, savedAt: Date.now() });
    slots.status(`saved to slot ${n}`);
  } catch (e) {
    slots.status(`couldn't save: ${e.message ?? e}`, true);
  }
  refreshSlots();
}

async function loadState(n) {
  if (!emu) return;
  selectSlot(n);
  const key = romSaveKey;
  const record = await stateStore.load(key, n).catch(() => null);
  if (key !== romSaveKey || !emu) return; // the game changed meanwhile
  if (!record) return slots.status(`slot ${n} is empty`);
  try {
    emu.load_state(record.state);
  } catch (e) {
    slots.status(`couldn't load slot ${n}: ${e.message ?? e}`, true);
    return;
  }
  draw(); // the state's own picture, even while paused
  debug.update(emu);
  slots.status(`loaded slot ${n}, saved ${savedAgo(record.savedAt)}`);
}

// Debugger. Stepping pauses the game first, and opens the panel to show
// where it stopped.
function stepInstruction() {
  debugRun(() => {
    const cycles = emu.step();
    const state = emu.cpu_state();
    const halted = state.halted;
    state.free();
    const t = `${cycles.toLocaleString("en")} T-cycles`;
    if (halted) return `${t}, still in HALT: no enabled interrupt woke it`;
    // The longest instruction (CALL) takes 24; anything more was spent in HALT.
    return cycles > 24 ? `${t}, mostly asleep in HALT until an interrupt` : t;
  });
}

function stepFrame() {
  debugRun(() => {
    emu.resume_past_breakpoint();
    return emu.run_frame() ? `stopped at the breakpoint at $${hex(pcNow(), 4)}` : "1 frame";
  });
}

function debugRun(run) {
  if (!emu) return;
  if (!paused) setPaused(true);
  $("debug-panel").open = true;
  try {
    debug.note(run());
  } catch (e) {
    debug.note("");
    showError(String(e.message ?? e));
  }
  emu.take_audio(); // nothing plays while paused
  draw();
  collectSerial();
  debug.update(emu);
}

// Like the toolbar: a focused button would be pressed again by Enter or Space.
$("debug-panel").addEventListener("click", (e) => e.target.closest("button")?.blur());

$("debug-panel").addEventListener("toggle", () => {
  showPaused();
  debug.update(emu);
});
// Closed sections skip their work; show them up to date when opened.
for (const id of ["mem-section", "vram-section"]) {
  $(id).addEventListener("toggle", () => debug.update(emu));
}
$("vram-map").addEventListener("change", () => debug.update(emu));
$("vram-bank").addEventListener("change", () => debug.update(emu));

// Sound. Browsers only let audio start from a user gesture, so the first
// click, tap or key press anywhere switches it on (the Sound button handles
// its own clicks, or the same click would switch it on and then mute it).
async function startSound() {
  try {
    await audio.start();
  } catch (e) {
    console.warn("no sound:", e);
  }
  emu?.set_sample_rate(audio.sampleRate);
  showStatus();
}

function toggleSound() {
  if (!audio.running) {
    startSound();
  } else {
    audio.setMuted(!audio.muted);
    showStatus();
  }
}

for (const type of ["pointerdown", "keydown"]) {
  addEventListener(
    type,
    (e) => {
      if (!audio.running && !e.target.closest?.("#sound")) startSound();
    },
    { capture: true },
  );
}
showStatus();

// Browsers only reveal a gamepad after one of its buttons is pressed.
function showGamepads() {
  const pads = [...(navigator.getGamepads?.() ?? [])].filter((p) => p?.connected);
  $("pad").textContent = pads.length
    ? `🎮 ${pads.map((p) => p.id.replace(/\s*\(.*\)$/, "")).join(", ")}`
    : "🎮 press a button on a controller to use it";
}
addEventListener("gamepadconnected", showGamepads);
addEventListener("gamepaddisconnected", showGamepads);
showGamepads();

// On-screen controls. Each finger is its own pointer, so a thumb on the d-pad
// and one on A work together. Capturing the pointer keeps its moves coming
// after it slides off where it started; on every move we look again at what's
// under it, so a thumb can roll from B to A, or around the d-pad.
const touchPad = $("touch");
const dpad = touchPad.querySelector("[data-dpad]");
if (new URLSearchParams(location.search).has("touch")) {
  document.body.classList.add("force-touch");
}

function touchedMask(t, x, y) {
  if (t.onDpad) {
    const r = dpad.getBoundingClientRect();
    return dpadMask(x - (r.left + r.width / 2), y - (r.top + r.height / 2), r.width / 2);
  }
  const el = document.elementFromPoint(x, y)?.closest("[data-button]");
  return el && touchPad.contains(el) ? 1 << Number(el.dataset.button) : 0;
}

function onTouchMove(e) {
  const t = touches.get(e.pointerId);
  if (!t) return;
  const mask = touchedMask(t, e.clientX, e.clientY);
  if (mask & ~t.mask) navigator.vibrate?.(8); // a small tick on each new press
  t.mask = mask;
  showTouches();
  syncButtons();
}

function onTouchEnd(e) {
  if (!touches.delete(e.pointerId)) return;
  showTouches();
  syncButtons();
}

/** Lights up whatever any finger is holding. */
function showTouches() {
  let mask = 0;
  for (const t of touches.values()) mask |= t.mask;
  for (const el of touchPad.querySelectorAll("[data-button]")) {
    el.classList.toggle("pressed", (mask >> Number(el.dataset.button)) & 1);
  }
  for (const [arm, button] of [["right", 0], ["left", 1], ["up", 2], ["down", 3]]) {
    dpad.querySelector(`.${arm}`).classList.toggle("pressed", (mask >> button) & 1);
  }
}

touchPad.addEventListener("pointerdown", (e) => {
  e.preventDefault();
  try {
    touchPad.setPointerCapture(e.pointerId);
  } catch {
    // Synthetic or already-ended pointers can't be captured; moves still work.
  }
  touches.set(e.pointerId, { onDpad: Boolean(e.target.closest("[data-dpad]")), mask: 0 });
  onTouchMove(e);
});
touchPad.addEventListener("pointermove", onTouchMove);
touchPad.addEventListener("pointerup", onTouchEnd);
touchPad.addEventListener("pointercancel", onTouchEnd);
touchPad.addEventListener("contextmenu", (e) => e.preventDefault());

// Loading
$("file").addEventListener("change", (e) => {
  const file = e.target.files[0];
  if (file) loadRom(file);
});
const drop = $("drop");
drop.addEventListener("dragover", (e) => {
  e.preventDefault();
  drop.classList.add("dragging");
});
drop.addEventListener("dragleave", () => drop.classList.remove("dragging"));
drop.addEventListener("drop", (e) => {
  e.preventDefault();
  drop.classList.remove("dragging");
  const file = e.dataTransfer.files[0];
  if (file) loadRom(file);
});
