// Browser frontend: loads a ROM, runs gb-core at the Game Boy's real frame
// rate, draws to a canvas, forwards keyboard and gamepad input.
//
// ./pkg is generated by scripts/build-web.(ps1|sh). It is not checked in.
import init, { Emulator } from "./pkg/gb_wasm.js";
import { KEYMAP, gamepadsMask, withButton, changes } from "./input.js";

const FRAME_MS = 1000 / 59.7275; // DMG refresh rate

const $ = (id) => document.getElementById(id);
const canvas = $("screen");
const ctx = canvas.getContext("2d");
const image = ctx.createImageData(160, 144);

let emu = null;
let rafId = 0;
let lastTime = 0;
let backlog = 0;
let framesThisSecond = 0;
let fpsTimer = 0;
// Buttons held on the keyboard, and what the emulator was last told is held
// (keyboard OR gamepads), as masks indexed like gb_core::Button.
let keyMask = 0;
let sentMask = 0;

await init();

async function loadRom(file) {
  stop();
  $("error").hidden = true;
  $("serial").textContent = "";
  const bytes = new Uint8Array(await file.arrayBuffer());
  try {
    emu?.free();
    emu = new Emulator(bytes);
  } catch (e) {
    emu = null;
    showError(`Couldn't load ${file.name}: ${e.message ?? e}`);
    return;
  }
  $("title").textContent = emu.title() || file.name;
  $("hint").hidden = true;
  sentMask = 0; // a fresh emulator has nothing held; resend what is
  syncButtons();
  start();
}

function start() {
  lastTime = performance.now();
  fpsTimer = lastTime;
  backlog = 0;
  rafId = requestAnimationFrame(loop);
}

function stop() {
  cancelAnimationFrame(rafId);
  rafId = 0;
}

// requestAnimationFrame fires at the monitor's rate (60, 120, 144 Hz...),
// so run however many Game Boy frames are due, not one per callback.
function loop(now) {
  backlog += Math.min(now - lastTime, 250); // don't spiral after a stall
  lastTime = now;
  syncButtons(); // gamepads have no events: poll them every frame
  let ran = 0;
  try {
    while (backlog >= FRAME_MS) {
      emu.run_frame();
      backlog -= FRAME_MS;
      ran++;
    }
  } catch (e) {
    stop();
    draw();
    showError(String(e.message ?? e));
    return;
  }
  if (ran) draw();
  collectSerial();
  countFps(now, ran);
  rafId = requestAnimationFrame(loop);
}

function draw() {
  image.data.set(emu.framebuffer());
  ctx.putImageData(image, 0, 0);
}

function collectSerial() {
  const text = emu.take_serial();
  if (text) {
    $("serial").textContent += text;
    $("serial-panel").open = true;
  }
}

function countFps(now, ran) {
  framesThisSecond += ran;
  if (now - fpsTimer >= 1000) {
    $("fps").textContent = `${framesThisSecond} fps`;
    framesThisSecond = 0;
    fpsTimer = now;
  }
}

function showError(message) {
  const el = $("error");
  el.textContent = message;
  el.hidden = false;
}

// Input
// Tells the emulator about buttons whose combined (keyboard OR gamepad) state
// changed, so letting go of a key doesn't release a button held on the pad.
function syncButtons() {
  if (!emu) return;
  const mask = keyMask | gamepadsMask(navigator.getGamepads?.());
  for (const [button, pressed] of changes(sentMask, mask)) {
    emu.set_button(button, pressed);
  }
  sentMask = mask;
}

function onKey(e, pressed) {
  const button = KEYMAP[e.code];
  if (button === undefined) return;
  if (emu) e.preventDefault(); // without a game, let arrows scroll the page
  keyMask = withButton(keyMask, button, pressed);
  syncButtons();
}
addEventListener("keydown", (e) => onKey(e, true));
addEventListener("keyup", (e) => onKey(e, false));
// Switching tabs can swallow keyup events; don't leave buttons stuck down.
addEventListener("blur", () => {
  keyMask = 0;
  syncButtons();
});

// Browsers only reveal a gamepad after one of its buttons is pressed.
function showGamepads() {
  const pads = [...(navigator.getGamepads?.() ?? [])].filter((p) => p?.connected);
  $("pad").textContent = pads.length
    ? `🎮 ${pads.map((p) => p.id.replace(/\s*\(.*\)$/, "")).join(", ")}`
    : "🎮 press a button on a controller to use it";
}
addEventListener("gamepadconnected", showGamepads);
addEventListener("gamepaddisconnected", showGamepads);
showGamepads();

// Loading
$("file").addEventListener("change", (e) => {
  const file = e.target.files[0];
  if (file) loadRom(file);
});
const drop = $("drop");
drop.addEventListener("dragover", (e) => {
  e.preventDefault();
  drop.classList.add("dragging");
});
drop.addEventListener("dragleave", () => drop.classList.remove("dragging"));
drop.addEventListener("drop", (e) => {
  e.preventDefault();
  drop.classList.remove("dragging");
  const file = e.dataTransfer.files[0];
  if (file) loadRom(file);
});
