// Browser frontend: loads a ROM, runs gb-core at the Game Boy's real frame
// rate, draws to a canvas, forwards keyboard, gamepad and touch input.
//
// ./pkg is generated by scripts/build-web.(ps1|sh). It is not checked in.
import init, { Emulator } from "./pkg/gb_wasm.js";
import { KEYMAP, gamepadsMask, dpadMask, withButton, changes } from "./input.js";
import { TURBO, framesDue, nextSpeed } from "./timing.js";

const $ = (id) => document.getElementById(id);
const canvas = $("screen");
const ctx = canvas.getContext("2d");
const image = ctx.createImageData(160, 144);

let emu = null;
// The loaded ROM, kept so Reset can power-cycle with it.
let rom = null;
let rafId = 0;
let lastTime = 0;
let backlog = 0;
let framesThisSecond = 0;
let fpsTimer = 0;
let paused = false;
let speed = 1; // from the speed button: 1, 2 or 4
let turbo = false; // Space held: fast-forward at TURBO
// Buttons held on the keyboard, and what the emulator was last told is held
// (keyboard OR gamepads OR touch), as masks indexed like gb_core::Button.
let keyMask = 0;
let sentMask = 0;
// Each finger on the on-screen controls: pointerId -> { onDpad, mask }.
const touches = new Map();

await init();

async function loadRom(file) {
  const bytes = new Uint8Array(await file.arrayBuffer());
  if (!boot(bytes, file.name)) {
    showStatus();
    return;
  }
  rom = bytes;
  $("title").textContent = emu.title() || file.name;
  $("hint").hidden = true;
  setPaused(false);
  showStatus();
}

/** Starts a fresh emulator on `bytes` (a power cycle). False if it won't load. */
function boot(bytes, name) {
  stop();
  $("error").hidden = true;
  $("serial").textContent = "";
  try {
    emu?.free();
    emu = new Emulator(bytes);
  } catch (e) {
    emu = null;
    showError(`Couldn't load ${name}: ${e.message ?? e}`);
    return false;
  }
  sentMask = 0; // a fresh emulator has nothing held; resend what is
  syncButtons();
  return true;
}

// Reset: the DMG has no reset button, so power-cycle with the same ROM.
// TODO(milestone 5): keep battery-backed cartridge RAM across this.
function reset() {
  if (!rom || !boot(rom, $("title").textContent)) return;
  draw();
  if (!paused) start();
}

function setPaused(on) {
  paused = on;
  if (paused) stop();
  else if (emu && !rafId) start();
  $("paused").hidden = !paused;
  showStatus();
}

function cycleSpeed() {
  speed = nextSpeed(speed);
  showStatus();
}

function start() {
  lastTime = performance.now();
  fpsTimer = lastTime;
  framesThisSecond = 0;
  backlog = 0;
  rafId = requestAnimationFrame(loop);
}

function stop() {
  cancelAnimationFrame(rafId);
  rafId = 0;
}

// requestAnimationFrame fires at the monitor's rate (60, 120, 144 Hz...),
// so run however many Game Boy frames are due, not one per callback.
// Fast-forward just makes more frames due; only the last one gets drawn.
function loop(now) {
  const due = framesDue(backlog, now - lastTime, turbo ? TURBO : speed);
  backlog = due.backlog;
  lastTime = now;
  syncButtons(); // gamepads have no events: poll them every frame
  let ran = 0;
  try {
    for (; ran < due.frames; ran++) emu.run_frame();
  } catch (e) {
    stop();
    draw();
    showError(String(e.message ?? e));
    return;
  }
  if (ran) draw();
  collectSerial();
  countFps(now, ran);
  rafId = requestAnimationFrame(loop);
}

function draw() {
  image.data.set(emu.framebuffer());
  ctx.putImageData(image, 0, 0);
}

function collectSerial() {
  const text = emu.take_serial();
  if (text) {
    $("serial").textContent += text;
    $("serial-panel").open = true;
  }
}

function countFps(now, ran) {
  framesThisSecond += ran;
  if (now - fpsTimer >= 1000) {
    $("fps").textContent = `${framesThisSecond} fps`;
    framesThisSecond = 0;
    fpsTimer = now;
  }
}

/** Updates the toolbar buttons to match the current state. */
function showStatus() {
  const loaded = Boolean(emu);
  for (const id of ["pause", "reset", "speed"]) $(id).disabled = !loaded;
  $("pause").textContent = paused ? "Resume" : "Pause";
  $("pause").setAttribute("aria-pressed", String(paused));
  const shown = turbo ? TURBO : speed;
  $("speed").textContent = `${shown}×`;
  $("speed").classList.toggle("fast", shown > 1);
  if (paused) $("fps").textContent = "paused";
}

function showError(message) {
  const el = $("error");
  el.textContent = message;
  el.hidden = false;
}

// Input
// Tells the emulator about buttons whose combined (keyboard OR gamepad) state
// changed, so letting go of a key doesn't release a button held on the pad.
function syncButtons() {
  if (!emu) return;
  let mask = keyMask | gamepadsMask(navigator.getGamepads?.());
  for (const t of touches.values()) mask |= t.mask;
  for (const [button, pressed] of changes(sentMask, mask)) {
    emu.set_button(button, pressed);
  }
  sentMask = mask;
}

function onKey(e, pressed) {
  const button = KEYMAP[e.code];
  if (button === undefined) return;
  if (emu) e.preventDefault(); // without a game, let arrows scroll the page
  keyMask = withButton(keyMask, button, pressed);
  syncButtons();
}
addEventListener("keydown", (e) => onKey(e, true));
addEventListener("keyup", (e) => onKey(e, false));
// Switching tabs can swallow keyup events; don't leave buttons stuck down.
addEventListener("blur", () => {
  keyMask = 0;
  syncButtons();
  setTurbo(false);
});

// Emulator controls: P pause, R reset, F cycle speed, hold Space to fast-forward.
function setTurbo(on) {
  if (turbo === on) return;
  turbo = on;
  showStatus();
}
addEventListener("keydown", (e) => {
  if (!emu || e.ctrlKey || e.metaKey || e.altKey) return;
  if (e.code === "Space") {
    e.preventDefault(); // don't scroll the page
    setTurbo(true);
    return;
  }
  if (e.repeat) return;
  if (e.code === "KeyP") setPaused(!paused);
  else if (e.code === "KeyR") reset();
  else if (e.code === "KeyF") cycleSpeed();
});
addEventListener("keyup", (e) => {
  if (e.code === "Space") setTurbo(false);
});
// Drop focus after a click: a focused button would also be "clicked" by
// Enter (Start) or Space (fast-forward) during play.
for (const [id, action] of [["pause", () => setPaused(!paused)], ["reset", reset], ["speed", cycleSpeed]]) {
  $(id).addEventListener("click", (e) => {
    action();
    e.currentTarget.blur();
  });
}
showStatus();

// Browsers only reveal a gamepad after one of its buttons is pressed.
function showGamepads() {
  const pads = [...(navigator.getGamepads?.() ?? [])].filter((p) => p?.connected);
  $("pad").textContent = pads.length
    ? `🎮 ${pads.map((p) => p.id.replace(/\s*\(.*\)$/, "")).join(", ")}`
    : "🎮 press a button on a controller to use it";
}
addEventListener("gamepadconnected", showGamepads);
addEventListener("gamepaddisconnected", showGamepads);
showGamepads();

// On-screen controls. Each finger is its own pointer, so a thumb on the d-pad
// and one on A work together. Capturing the pointer keeps its moves coming
// after it slides off where it started; on every move we look again at what's
// under it, so a thumb can roll from B to A, or around the d-pad.
const touchPad = $("touch");
const dpad = touchPad.querySelector("[data-dpad]");
if (new URLSearchParams(location.search).has("touch")) {
  document.body.classList.add("force-touch");
}

function touchedMask(t, x, y) {
  if (t.onDpad) {
    const r = dpad.getBoundingClientRect();
    return dpadMask(x - (r.left + r.width / 2), y - (r.top + r.height / 2), r.width / 2);
  }
  const el = document.elementFromPoint(x, y)?.closest("[data-button]");
  return el && touchPad.contains(el) ? 1 << Number(el.dataset.button) : 0;
}

function onTouchMove(e) {
  const t = touches.get(e.pointerId);
  if (!t) return;
  const mask = touchedMask(t, e.clientX, e.clientY);
  if (mask & ~t.mask) navigator.vibrate?.(8); // a small tick on each new press
  t.mask = mask;
  showTouches();
  syncButtons();
}

function onTouchEnd(e) {
  if (!touches.delete(e.pointerId)) return;
  showTouches();
  syncButtons();
}

/** Lights up whatever any finger is holding. */
function showTouches() {
  let mask = 0;
  for (const t of touches.values()) mask |= t.mask;
  for (const el of touchPad.querySelectorAll("[data-button]")) {
    el.classList.toggle("pressed", (mask >> Number(el.dataset.button)) & 1);
  }
  for (const [arm, button] of [["right", 0], ["left", 1], ["up", 2], ["down", 3]]) {
    dpad.querySelector(`.${arm}`).classList.toggle("pressed", (mask >> button) & 1);
  }
}

touchPad.addEventListener("pointerdown", (e) => {
  e.preventDefault();
  try {
    touchPad.setPointerCapture(e.pointerId);
  } catch {
    // Synthetic or already-ended pointers can't be captured; moves still work.
  }
  touches.set(e.pointerId, { onDpad: Boolean(e.target.closest("[data-dpad]")), mask: 0 });
  onTouchMove(e);
});
touchPad.addEventListener("pointermove", onTouchMove);
touchPad.addEventListener("pointerup", onTouchEnd);
touchPad.addEventListener("pointercancel", onTouchEnd);
touchPad.addEventListener("contextmenu", (e) => e.preventDefault());

// Loading
$("file").addEventListener("change", (e) => {
  const file = e.target.files[0];
  if (file) loadRom(file);
});
const drop = $("drop");
drop.addEventListener("dragover", (e) => {
  e.preventDefault();
  drop.classList.add("dragging");
});
drop.addEventListener("dragleave", () => drop.classList.remove("dragging"));
drop.addEventListener("drop", (e) => {
  e.preventDefault();
  drop.classList.remove("dragging");
  const file = e.dataTransfer.files[0];
  if (file) loadRom(file);
});
